Support @Max constraint for parameter of int
JavaUnit/AutoParams pull request #200
Opened 2021-05-04 10:59 UTC by Rebwon

#185 기여합니다.

2021-05-04 12:55 UTC, gyuwon commented on autoparams/src/test/java/org/javaunit/autoparams/test/SpecsForMax.java
> +public class SpecsForMax {
다음 테스트를 추가해주세요.

```java
@ParameterizedTest
@AutoSource(repeat = 100)
void sut_accepts_max_constraint_with_big_value_for_int(@Max(0x80000000) int value) {
    assertThat(value).isLessThanOrEqualTo(Integer.MAX_VALUE);
}
```

2021-05-05 02:55 UTC, gyuwon requested changes

2021-05-05 02:55 UTC, gyuwon commented on autoparams/src/test/java/org/javaunit/autoparams/test/SpecsForMax.java
> +public class SpecsForMax {
@Rebwon 죄송합니다. 제가 테스트 케이스를 잘 못 드렸습니다. 이렇게 테스트를 고쳐주세요.

```java
    @ParameterizedTest
    @AutoSource(repeat = 100)
    void sut_accepts_max_constraint_with_big_value_for_int(@Min(0) @Max(0x80000000L) int value) {
        assertThat(value).isGreaterThanOrEqualTo(0);
    }
```

2021-05-05 09:08 UTC, Rebwon commented on autoparams/src/test/java/org/javaunit/autoparams/test/SpecsForMax.java
> +public class SpecsForMax {
@gyuwon 테스트 케이스의 Max의 값이 L로 표현되어야하는 이유가 있나요? 0 < ~0x80000000 는 True라는 케이스를 검증하도록 하신 것 같아 여쭤봅니다.

2021-05-05 11:17 UTC, gyuwon commented on autoparams/src/test/java/org/javaunit/autoparams/test/SpecsForMax.java
> +public class SpecsForMax {
`0x80000000`는 Java에서 `int` 값을 나타내서 음수거든요. 'L'을 붙여야 `long` 값이 됩니다.

2021-05-05 11:45 UTC, Rebwon commented on autoparams/src/test/java/org/javaunit/autoparams/test/SpecsForMax.java
> +public class SpecsForMax {
@gyuwon 테스트 수정 완료했습니다.

2021-05-05 11:50 UTC, gyuwon commented on autoparams/src/main/java/org/javaunit/autoparams/generator/IntegerGenerator.java
> +                return (int) Math.max(
이렇게 하면 코드가 짧아지고 모든 테스트가 통과할 것 같습니다.

```suggestion
                return (int) Math.min(Integer.MAX_VALUE, annotation.value());
```

2021-05-05 11:56 UTC, Rebwon commented on autoparams/src/main/java/org/javaunit/autoparams/generator/IntegerGenerator.java
> +                return (int) Math.max(
@gyuwon 변경사항 반영했습니다. squash 해서 최종적으로 다시 올릴까요?

2021-05-05 11:58 UTC, gyuwon commented on autoparams/src/main/java/org/javaunit/autoparams/generator/IntegerGenerator.java
> +                return (int) Math.max(
@Rebwon 직접 판단해주세요. Squash 하실 거면 기다리겠습니다. :)

2021-05-05 12:03 UTC, Rebwon commented on autoparams/src/main/java/org/javaunit/autoparams/generator/IntegerGenerator.java
> +                return (int) Math.max(
@gyuwon squash 했습니다. 기여하는 동안 테스트 작성하신 부분과 변경사항에 대해 좋은 학습이 되었습니다. 리뷰 감사합니다 :)

2021-05-05 12:05 UTC, gyuwon approved these changes

2021-05-05 12:05 UTC, merged

2021-05-05 12:09 UTC, gyuwon commented on autoparams/src/main/java/org/javaunit/autoparams/generator/IntegerGenerator.java
> +                return (int) Math.max(
@Rebwon 수고 많으셨습니다 :)