Support @Min constraint for parameter of long
JavaUnit/AutoParams pull request #201
Opened 2021-05-04 13:37 UTC by sogoagain

안녕하세요 :)
프로젝트 코드가 정리되었다고 해서 구경차 왔다가 `good-first-issue`를 발견하여 기여합니다. ㅎㅎ
코드 보며 많이 배우는 계기가 되었습니다.
좋은 프로젝트/코드 감사합니다.

- 관련 이슈: https://github.com/JavaUnit/AutoParams/issues/190

2021-05-05 02:43 UTC, gyuwon requested changes

2021-05-05 02:43 UTC, gyuwon commented on autoparams/src/main/java/org/javaunit/autoparams/generator/LongGenerator.java
> +                return Math.max(Long.MIN_VALUE, annotation.value());
`annotation.value()` 형식이 `long`이니 `Math.max`는 필요하지 않을 것 같습니다.

2021-05-06 16:20 UTC, sogoagain commented on autoparams/src/main/java/org/javaunit/autoparams/generator/LongGenerator.java
> +                return Math.max(Long.MIN_VALUE, annotation.value());
리뷰 감사드립니다. 😀  
반영 하였습니다 :)

2021-05-07 00:50 UTC, gyuwon approved these changes

2021-05-07 00:51 UTC, gyuwon commented on autoparams/src/main/java/org/javaunit/autoparams/generator/LongGenerator.java
> +                return Math.max(Long.MIN_VALUE, annotation.value());
수고하셨습니다 :)

2021-05-07 00:51 UTC, merged