#9 Support JavaTimeGenerator
JavaUnit/AutoParams pull request #54
Opened 2021-03-17 10:33 UTC by cg4jins

LocalDate, LocalTime, LocalDateTime 을 지원하도록 했습니다.

2021-03-17 15:18 UTC, gyuwon commented
@cg4jins 코드 기여 고맙습니다! 🖖

병합 커밋이 없도록 리베이스 부탁드립니다.

2021-03-18 01:33 UTC, jwChung reviewed
기여 감사드립니다. 몇 가지 의견남깁니다. 검토 부탁드려요 :)

2021-03-18 01:33 UTC, jwChung commented on autoparams/src/main/java/org/javaunit/autoparams/ComplexObjectConstructorResolver.java
> +import java.time.LocalTime;
불필요한 import 구문 같습니다.

2021-03-18 01:33 UTC, jwChung commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +    }
각각의 타입별로 테스트가 작성되면 좋을 것 같습니다. 증상(실패 메세지)이 많으면 원인 파악에 도움이 된다고 생각합니다. 이 관점에서 [ParameterObject](https://refactoring.guru/introduce-parameter-object)인 JavaTimeObject 타입이 불필요할 것 같습니다.

2021-03-18 01:33 UTC, jwChung commented on autoparams/src/main/java/org/javaunit/autoparams/JavaTimeGenerator.java
> +public class JavaTimeGenerator implements ObjectGenerator {
`JavaTimeGenerator`에서 Java단어는 불필요할 것 같고, 날짜와 시간 발생기란 의미에서 `DateAndTimeGenerator` 제안드려봅니다.

/cc @gyuwon @mhyeon-lee

2021-03-18 02:53 UTC, gyuwon requested changes
커밋에 class 파일들이 들어왔네요. 커밋에 남지 않도록 삭제 부탁드립니다.

2021-03-18 02:56 UTC, gyuwon requested changes

2021-03-18 02:56 UTC, gyuwon commented on autoparams/src/main/java/org/javaunit/autoparams/JavaTimeGenerator.java
> +public class JavaTimeGenerator implements ObjectGenerator {
`public`은 필요 없기 보다는 공개 API를 변경하는 코드이기 때문에 제거되어야 합니다. 수정 부탁드립니다.

2021-03-18 03:12 UTC, jwChung commented on autoparams/src/main/java/org/javaunit/autoparams/ComplexObjectConstructorResolver.java
> +import java.time.LocalTime;
아 제가 잘못봤네요. 밑에 사용하는 코드가 있군요.

2021-03-18 03:13 UTC, jwChung approved these changes

2021-03-18 03:20 UTC, cg4jins commented
@jwChung @gyuwon 리뷰 코멘트 반영했습니다.

2021-03-18 08:53 UTC, mhyeon-lee commented on autoparams/src/main/java/org/javaunit/autoparams/JavaTimeGenerator.java
> +public class JavaTimeGenerator implements ObjectGenerator {
참고로 spring 에서는 Date, Time 대상으로 `Jsr310Converters` 라는 이름을 사용했네요

https://github.com/spring-projects/spring-data-commons/blob/master/src/main/java/org/springframework/data/convert/Jsr310Converters.java#L50

Jsr310 이름을 사용하자는건 아니고, 다른 곳에서 어떻게 사용했는지 참고차 링크 남깁니다.

2021-03-18 09:09 UTC, jwChung commented on autoparams/src/main/java/org/javaunit/autoparams/ComplexObjectConstructorResolver.java
> +            LocalDate.class, LocalTime.class, LocalDateTime.class));
@cg4jins #64 PR 때문에 컨플릿이 발생한 것 같습니다. 두 라인 삭제해야하지 않을까 합니다. :)

2021-03-18 13:25 UTC, gyuwon commented on .gitignore
> +out
이건 어떤 프로그램이 만드나요?

2021-03-18 13:40 UTC, cg4jins commented on .gitignore
> +out
@gyuwon 회사 intellij 버전이 낮은데 거기서 out 디렉토리를 만드네요.
집에서는 최신버전이라 관계 없고요.

2021-03-18 13:47 UTC, gyuwon commented on .gitignore
> +out
이 변경은 제가 별도의 커밋으로 main 브랜치에 반영하겠습니다. 반영 후 리베이스 부탁드립니다.

2021-03-18 13:47 UTC, gyuwon commented
커밋 트리에 class 파일이 들어가지 않고 빌드 실패가 없도록 리베이스 부탁 드립니다.

2021-03-18 13:50 UTC, gyuwon requested changes

2021-03-18 13:50 UTC, gyuwon commented on .gitignore
> +out
.gitignore 변경 main 브랜치에 반영되었습니다.

2021-03-18 14:04 UTC, cg4jins commented on .gitignore
> +out
@gyuwon 리베이스 완료했습니다.

2021-03-18 23:37 UTC, gyuwon commented
@cg4jins 여전히 커밋 트리에 class 파일들이 들어가 있는데요, 커밋 5개를 squash 리베이스 해주시면 어떨까 싶습니다.

2021-03-19 05:26 UTC, closed without merging