#5 Support IntStream
JavaUnit/AutoParams pull request #55
Opened 2021-03-17 13:12 UTC by arron86

* `IntStream`을 지원합니다.
* distinct된 3개의 `int` 요소를 제공합니다.

2021-03-17 15:16 UTC, gyuwon commented
@jungseob-me 코드 기여 고맙습니다!

빌드가 깨지는 커밋이 없도록 f7caa8a 커밋과 7a9fd7b 커밋을 squash 해주시면 좋겠습니다.

2021-03-17 15:49 UTC, jwChung reviewed
@jungseob-me 기여 감사합니다. 사소한 의견 두 가지 드리니 검토 부탁드립니다 :)

2021-03-17 15:49 UTC, jwChung commented on autoparams/src/main/java/org/javaunit/autoparams/IntStreamGenerator.java
> +public class IntStreamGenerator implements ObjectGenerator {
`IntStreamGenerator`  은  `IntStream` 값을 제공하지만, public API로 공개될 필요가 있을지 의문입니다.

2021-03-17 15:49 UTC, jwChung commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +        assertThat(set).hasSize(array.length);
AutoParams이 제공하는 값은 일반적인 IntStream 값을 의미합니다. distinct를 사용해 유일한 값으로 제한할(specific) 필요가 있을지 생각해볼 문제입니다. 이런 관점에서 intStream이 제공하는 값의 개수가 3 이다는 검증 정도면 충분하지 않을까 생각합니다.

2021-03-18 01:55 UTC, jungseob-me commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +        assertThat(set).hasSize(array.length);
네, 이해했습니다.

2021-03-18 01:58 UTC, gyuwon requested changes

2021-03-18 01:58 UTC, gyuwon commented on autoparams/src/main/java/org/javaunit/autoparams/IntStreamGenerator.java
> +public class IntStreamGenerator implements ObjectGenerator {
이 부분은 공개 API가 변경되는 내용이기 때문에 비공개로 수정 부탁드립니다.

2021-03-18 01:59 UTC, jungseob-me commented on autoparams/src/main/java/org/javaunit/autoparams/IntStreamGenerator.java
> +public class IntStreamGenerator implements ObjectGenerator {
아! 네, 이해했습니다. 감사합니다.

2021-03-18 01:59 UTC, gyuwon commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +        assertThat(set).hasSize(array.length);
@jwChung 그런데 arbitrary의 의미를 생각하면 아예 고려하지 않을 수는 없을 것 같은데 어떻게 생각하시나요?

2021-03-18 02:09 UTC, jwChung commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +        assertThat(set).hasSize(array.length);
@gyuwon IntStream은 Set의미를 포함하지 않아서 여기선 고려하지 않아도 될 것 같아요.

size가 현재 3인데  customization 으로 수정할 수 있다면 AutoParams에서 만든 intStream 값에 intStream.distinct() 이렇게 사용할 수 있을 것 같습니다.

2021-03-18 02:16 UTC, gyuwon commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +        assertThat(set).hasSize(array.length);
@jwChung 이해했습니다.

2021-03-18 02:17 UTC, gyuwon approved these changes

2021-03-18 02:17 UTC, jungseob-me commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +        assertThat(set).hasSize(array.length);
@jwChung @gyuwon 사실 생각보다 distinct된 값으로 테스트를 하는 경우가 많아서 추후에 지원하는 기능으로 이슈 제안해보려고 생각했었습니다.

2021-03-18 02:18 UTC, jungseob-me commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +        assertThat(set).hasSize(array.length);
@jwChung 아, customization이 가능하면 되네요. 이해했습니다.

2021-03-18 03:10 UTC, jwChung commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +        assertThat(set).hasSize(array.length);
@jungseob-sh 님 작성하신 테스트가 유일성 검증 로직이 아직 남아 있는 것 같습니다. 다음과 같은 검증이면 충분하지 않을까 의견드립니다. :)

```
assertThat(intStream).isNotNull();
assertThat(intStream.count()).hasSize(3);
```

2021-03-18 03:15 UTC, jwChung requested changes
https://github.com/JavaUnit/AutoParams/pull/55/files#r596521689

변경이 필요한 것 같아서 request changes 요청드려요.

2021-03-18 03:37 UTC, jungseob-sh commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +        assertThat(set).hasSize(array.length);
@jwChung 아... 놓쳤습니다. 감사합니다.

2021-03-18 03:38 UTC, jungseob-sh commented
@jwChung PTAL, 테스트 로직에서 불필요한 유일성 검증 부분을 제거했습니다.

2021-03-18 03:42 UTC, jwChung approved these changes
@jungseob-sh 수고하셨습니다 👍

2021-03-18 06:27 UTC, merged

2021-03-18 08:46 UTC, gyuwon commented
@jungseob-sh 수고 정말 많으셨습니다! 🖖