#51 Support CharacterGenerator
JavaUnit/AutoParams pull request #57
Opened 2021-03-17 13:42 UTC by sogoagain

안녕하세요 :)
프로젝트 구경하다 #51 이슈를 발견하여 작업해보았습니다.
리뷰 부탁드려요. 감사합니다!

## 상세

- `char`/`Character` 값 생성 기능 구현

2021-03-17 15:08 UTC, gyuwon commented
@sogoagain 기여 고맙습니다!

코드 충돌이 발생하니 리베이스 부탁드립니다. 리베이스 하실 때 빌드가 실패하는 커밋이 포함되지 않도록 72e0464 커밋과 df0f772 커밋을 squash 해주시면 좋겠습니다.

2021-03-17 15:37 UTC, sogoagain commented
> @sogoagain 기여 고맙습니다!
> 
> 코드 충돌이 발생하니 리베이스 부탁드립니다. 리베이스 하실 때 빌드가 실패하는 커밋이 포함되지 않도록 [72e0464](https://github.com/JavaUnit/AutoParams/commit/72e0464f6025ffce1bb1f0106f0ba093fbfb2071) 커밋과 [df0f772](https://github.com/JavaUnit/AutoParams/commit/df0f77255f0e29217ab3da18f8a7646075365522) 커밋을 squash 해주시면 좋겠습니다.

네! 말씀주신대로 rebase를 통해 충돌해결하였습니다.
감사합니다.

2021-03-17 16:32 UTC, jwChung reviewed
기여 감사합니다. 사소한 의견 몇 가지 남겼습니다. 검토 부탁드려요 :)

2021-03-17 16:32 UTC, jwChung commented on autoparams/src/main/java/org/javaunit/autoparams/CharacterGenerator.java
> +public class CharacterGenerator implements ObjectGenerator {
`CharacterGenerator`를  public API(public 접근자)로 노출할 필요가 있을지 의문입니다.

2021-03-17 16:32 UTC, jwChung commented on autoparams/src/main/java/org/javaunit/autoparams/CharacterGenerator.java
> +        return Optional.of((char) RANDOM.nextInt(Character.MAX_VALUE + 1));
```suggestion
        int exclusiveCharUpperBound = Character.MAX_VALUE + 1;
        return Optional.of((char) RANDOM.nextInt(exclusiveCharUpperBound));
```

사소한 의견입니다만, `exclusiveCharacterUpperBound` 라는 이름의 로컬 변수를 사용하면 코드의 의도가 들어나서 좋을 것 같습니다. :)

2021-03-17 16:32 UTC, jwChung commented on autoparams/src/test/java/org/javaunit/autoparams/AutoArgumentsProviderSpecs.java
> +        assertThat(actual).hasSize(count);
이해하기 쉬운 테스트로 검증한다는 입장에서 작성하신 `sut_correctly_generates_characters` 와 같은 테스트로 구현을 검증하는 것이  충분하지 않을까 합니다.

추축컨데 작성하신 검증 방식은 @gyuwon 님이 초기 구현(`@AutoSource` 가 동작하지 않는 상황)에서 선택한 검증 방법이 아닐까 합니다.  제 생각이 틀릴 수 있으니 @gyuwon 님 의견 부탁드리겠습니다.

2021-03-17 16:42 UTC, jwChung commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +        assertThat(value2).isInstanceOf(Character.class);
강한 의견은 아닙니다만 char/Character 검증을 각각의 테스트로 구분하는 것이 어떨까 합니다. 증상(실패 메세지)이 많으면 원인 파악에 도움이 된다고 생각합니다.

2021-03-18 01:14 UTC, gyuwon requested changes

2021-03-18 01:14 UTC, gyuwon commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +        assertThat(value2).isInstanceOf(Character.class);
동의합니다.

2021-03-18 01:14 UTC, gyuwon commented on autoparams/src/main/java/org/javaunit/autoparams/CharacterGenerator.java
> +public class CharacterGenerator implements ObjectGenerator {
이건 공개 API를 변경하는 것이기 때문에 꼭 수정되어야 하는 내용입니다. 비공개로 변경 부탁드립니다.

2021-03-18 01:14 UTC, gyuwon commented on autoparams/src/test/java/org/javaunit/autoparams/AutoArgumentsProviderSpecs.java
> +        assertThat(actual).hasSize(count);
@jwChung 정확히 맞습니다. 이 테스트 클래스는 `@AutoSource`가 제대로 동작하기 전에 어쩔 수 없이 만든 클래스로 가급적 확장하지 않고 `AutoSourceSpecs` 테스트 클래스를 사용하는 것이 바람직합니다.

2021-03-18 01:15 UTC, gyuwon commented
@sogoagain 리베이스 감사드립니다! 👍

2021-03-18 05:01 UTC, sogoagain commented on autoparams/src/main/java/org/javaunit/autoparams/CharacterGenerator.java
> +public class CharacterGenerator implements ObjectGenerator {
네, 다른 ObjectGenerator들을 참고하여 수정하였습니다 :)
감사합니다! 👍

2021-03-18 05:03 UTC, jwChung approved these changes

2021-03-18 05:03 UTC, sogoagain commented on autoparams/src/main/java/org/javaunit/autoparams/CharacterGenerator.java
> +        return Optional.of((char) RANDOM.nextInt(Character.MAX_VALUE + 1));
네! 의견 주신것을 반영해보았는데 확실히 의도가 잘 드러나네요. 감사합니다.
혹시, `exclusiveCharUpperBound`와 같은 변수를 상수 필드로 추출하는 것은 어떻게 생각하시나요?

2021-03-18 05:04 UTC, jwChung commented
@sogoagain 수고하셨습니다. 💯

2021-03-18 05:04 UTC, sogoagain commented on autoparams/src/test/java/org/javaunit/autoparams/AutoArgumentsProviderSpecs.java
> +        assertThat(actual).hasSize(count);
네, 의견 주신 것을 반영하여 `AutoArgumentsProviderSpecs`에 작성했던 테스트 케이스는 삭제하였습니다!

2021-03-18 05:05 UTC, sogoagain commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +        assertThat(value2).isInstanceOf(Character.class);
`char`, `Character` 각각을 검증하도록 테스트 케이스를 분리하였고,
네이밍도 다른 테스트 케이스를 참고하여 수정하였습니다. 감사합니다! :)

2021-03-18 05:07 UTC, jwChung commented on autoparams/src/main/java/org/javaunit/autoparams/CharacterGenerator.java
> +        return Optional.of((char) RANDOM.nextInt(Character.MAX_VALUE + 1));
@sogoagain 상수 필드로 추출하면 어떤 장점이 있을까요?

2021-03-18 05:27 UTC, sogoagain commented on autoparams/src/main/java/org/javaunit/autoparams/CharacterGenerator.java
> +        return Optional.of((char) RANDOM.nextInt(Character.MAX_VALUE + 1));
@jwChung 변하지 않는 값이라 습관적으로 상수 필드로 추출하는 것은 어떨까 생각해보았는데, 현재 상황에서는 이렇다할 장점이 없을 것 같습니다. :)
추출한 로컬 변수에 `final` 키워드를 붙여 변하지 않는 값이란 것을 나타내는 정도가 좋을 것 같단 생각이 드네요.

2021-03-18 10:17 UTC, jwChung commented on autoparams/src/main/java/org/javaunit/autoparams/CharacterGenerator.java
> +        return Optional.of((char) RANDOM.nextInt(Character.MAX_VALUE + 1));
상수 필드로 써도 좋을 것 같습니다. 저도 큰 차이는 못 느끼겠습니다.

2021-03-18 12:39 UTC, gyuwon approved these changes

2021-03-18 12:39 UTC, merged

2021-03-18 12:40 UTC, gyuwon commented
@sogoagain 수고 많으셨습니다! 🖖

2021-03-18 14:10 UTC, sogoagain commented
@jwChung @gyuwon 감사합니다!