Apply randomness to DateAndTimeGenerator
JavaUnit/AutoParams pull request #83
Opened 2021-03-20 08:59 UTC by cg4jins

#9

2021-03-20 10:44 UTC, gyuwon commented
@cg4jins 새 기능에 대한 테스트 코드가 필요할 것 같습니다.

2021-03-20 10:44 UTC, gyuwon requested changes
@cg4jins 새 기능에 대한 테스트 코드가 필요할 것 같습니다.

2021-03-20 10:52 UTC, cg4jins commented
@gyuwon 어떻게 테스트코드를 만들어야 할 지 딱히 좋은 아이디어가 안 떠오르네요.

+-2년을 넘지 않는지 체크해볼까요?

2021-03-20 11:33 UTC, cg4jins commented
@gyuwon 테스트 코드를 좀 추가해 봤습니다.

2021-03-20 12:07 UTC, gyuwon requested changes

2021-03-20 12:07 UTC, gyuwon commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +                LocalDateTime.now().plusDays(DateAndTimeGenerator.RANGE_DAYS));
기존 테스트를 수정하지 말고 새 테스트를 만드는 것이 좋겠습니다.

2021-03-20 14:03 UTC, cg4jins commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +                LocalDateTime.now().plusDays(DateAndTimeGenerator.RANGE_DAYS));
새 테스트를 만들었습니다.

2021-03-21 03:14 UTC, gyuwon commented
@cg4jins '테스트가 실패하는 것을 확인하기 전까지 테스트를 믿지 마라'는 말이있습니다. 이 PR 운영 코드의 수정된 부분을 모두 제외시켜도 새로 추가된 모든 테스트 코드는 통과(false-negative)할 것 같습니다. 테스트 코드의 검증력이 없는 것이죠.

@jwChung 혹시 이 작업의 테스트 작성에 대한 도움을 주실 수 있을까요?

2021-03-21 03:29 UTC, jwChung commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +            .isBetween(LocalDateTime.now().minusDays(DateAndTimeGenerator.RANGE_DAYS),
package-private를 테스트에서 접근하는 것은 부적절하지 않을까 합니다. 테스트가 자세한 프로덕션 내용을 알게되는 상황이라서요. 테스트는 클라이언트처럼 동작해서 public API로만 피드백을 주는 것이 프로덕션 코드에 refactoring 기회를 넓혀 줍니다.

package-private 에 접근을 못하도록 아예 강제를 했으면 좋겠네요. production / test 를 각각의 모듈로 분리하는 것 외에 다른 방법은 없을까요? /cc @mhyeon-lee  @gyuwon

2021-03-21 03:43 UTC, gyuwon commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +            .isBetween(LocalDateTime.now().minusDays(DateAndTimeGenerator.RANGE_DAYS),
빌어먹을 Java 컨벤션 중 하나죠. Ja린이라 이걸 어떻게 해결해야 할지는 잘 모르겠습니다.

2021-03-21 03:49 UTC, gyuwon requested changes

2021-03-21 03:49 UTC, gyuwon commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +            .isBetween(LocalDateTime.now().minusDays(DateAndTimeGenerator.RANGE_DAYS),
그런데 모듈 분리로 해결이 되나요?

2021-03-21 03:53 UTC, gyuwon requested changes

2021-03-21 03:53 UTC, gyuwon commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +            .isBetween(LocalDateTime.now().minusDays(DateAndTimeGenerator.RANGE_DAYS),
우선 이 PR에서는 상수 접근 제한을 `private`으로 바꾸는 것이 좋겠습니다.

2021-03-21 03:57 UTC, mhyeon-lee commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +            .isBetween(LocalDateTime.now().minusDays(DateAndTimeGenerator.RANGE_DAYS),
저는 production 의 상수를 `private` 으로 하고 
테스트에 별도로 상수를 선언해서 검증에서 사용합니다.

production 의 상수가 변경되면 테스트가 깨지면서 알려줄거고 그때 테스트의 상수를 수정합니다.

2021-03-21 04:13 UTC, gyuwon commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +            .isBetween(LocalDateTime.now().minusDays(DateAndTimeGenerator.RANGE_DAYS),
@mhyeon-lee 이 PR에는 해당되지 않지만 패키지 내부에서 공유되는 상수는 일반적인 Java 컨벤션을 따르면 항상 테스트에 노출되는데 이런 문제는 해결방법이 있나요?

2021-03-21 04:25 UTC, mhyeon-lee commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +            .isBetween(LocalDateTime.now().minusDays(DateAndTimeGenerator.RANGE_DAYS),
아니요 기본적으로는 같은 패키지에 `package-private` 은 테스트에도 노출됩니다.

2021-03-21 04:25 UTC, jwChung commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +    }
@cg4jins  스레드로 표현되는 게 좋을 것 같아서 여기서 의견드려요 :)

@gyuwon 님이 잘 설명하실 수 있는데 왜 제게 부탁하시는지 모르겠지만 ㅋㅋ 제 생각을 말씀드리자면,

randomness는 테스트 불가능하기 때문에 외부에서 결정된 값이 주어져야 합니다. seed 값을 public API로 설정하거나, Random 인스턴스를 외부에서 넣어 주는 방식으로요. 얼마전 사내에서 이 문제로 seed 값 설정 기능을 넣었습니다. seed 값이 있으며 임의로 생성되는 fixture 재현할 수도 있고 해서요.

현재 상황에선 아래와 같이 임의 값을 많이 만들어서 now 를 벗어 난다 정도를 테스트할 수 있을 것 같습니다. [저도 특별한 방법이 없어서 그렇게 했습니다. ㅋㅋ](https://github.com/hedgehogqa/fsharp-hedgehog/pull/163#discussion_r197994068) #76 을 먼저 제안 드린 것도 이런 테스트에 사용할 생각이었습니다. (/cc @gyuwon @mhyeon-lee )

```java
public test(List<LocalDate> x, List<LocalDate> y, List<LocalDate> z  ... ) {
LocalDate min = ...
LocalDate max = ...

var period = max - min;

//  assert "period는 어느 정도 된다."
}
````
@gyuwon 님 더 좋은 방법이 있을까요?

2021-03-21 04:31 UTC, jwChung commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +            .isBetween(LocalDateTime.now().minusDays(DateAndTimeGenerator.RANGE_DAYS),
ja린이 질문 좀 드릴께요 ㅜㅜ 모듈을 분리하더라도 같은 패키지 명이면 package-private에 접근 가능한가요?

2021-03-21 04:36 UTC, mhyeon-lee commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +            .isBetween(LocalDateTime.now().minusDays(DateAndTimeGenerator.RANGE_DAYS),
모듈이라는게 gradle module 인가요? 패키지인가요?
둘다 어찌 됐든 같은 패키지명이면 접근됩니다.

AutoParams 를 dependency 로 가지는 프로젝트에서 의도적으로 `org.javaunit.autoparams` 패키지를 만들고 클래스를 만들면 `package-private` 에 접근할 수 있습니다. 멋지죠?

2021-03-21 04:48 UTC, mhyeon-lee commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +            .isBetween(LocalDateTime.now().minusDays(DateAndTimeGenerator.RANGE_DAYS),
@jwChung 다른 프로젝트에서 `org.javaunit.autoparams` 패키지를 만들어서 `AutoArgumentsProvider` 에 접근했습니다.
@gyuwon 님이 https://github.com/JavaUnit/AutoParams/commit/6555d3678b388645e17c47bf42bb12c567ef07bb#diff-7d7c2c03a4014d47ab4bb15201d8a6e93afb08b8391a67dbe99468106be5b3acR13 여기에서 public 을 제거했지만 접근할 수 있습니다.

<img width="822" alt="스크린샷 2021-03-21 오후 1 46 18" src="https://user-images.githubusercontent.com/5206572/111894166-d6736880-8a4b-11eb-8d5c-ca1e7f239c97.png">

2021-03-21 05:19 UTC, cg4jins commented
@gyuwon 
조언해 주신 false-negative 코드를 수정해 봤습니다.
```java
void sut_LocalTime_randomness(LocalTime value1, LocalTime value2) {
        assertThat(value1).isNotEqualTo(value2);
}
```

2021-03-21 07:41 UTC, jwChung commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +            .isBetween(LocalDateTime.now().minusDays(DateAndTimeGenerator.RANGE_DAYS),
@mhyeon-lee 이건 구조는 넌센스일까요?

![image](https://user-images.githubusercontent.com/3784448/111897606-383fcc80-8a64-11eb-9aaa-8068573e6d3c.png)

/cc @gyuwon

2021-03-21 07:44 UTC, gyuwon commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +            .isBetween(LocalDateTime.now().minusDays(DateAndTimeGenerator.RANGE_DAYS),
@jwChung 수십년간 고착된 악습에 대한 거침없는 도전이군요.
![image](https://user-images.githubusercontent.com/973743/111897656-9e2c5400-8a64-11eb-8ad8-3236a70c5622.png)

2021-03-21 07:47 UTC, mhyeon-lee commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +            .isBetween(LocalDateTime.now().minusDays(DateAndTimeGenerator.RANGE_DAYS),
@jwChung 
차라리 `org.javaunit.autopararms.test` 이게 나을거 같군요

2021-03-21 07:52 UTC, gyuwon commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +    }
새로 추가된 코드는

- 특정 범위에서
- 임의의 값을 추출하는

것으로 보입니다.

저라면 둘을 나눠서 테스트할 것 같아요.

```java
@ParameterizedTest
@AutoSource
void sut_creates_LocalDate_value_limited_to_correct_range(LocalDate value) {
    // value 범위 검증
    // - False-positive가 발생하지 않도록 생성 시각과 검증 시각 차 1초 정도 고려
}

@ParameterizedTest
@AutoSource
void sut_creates_arbitrary_LocalDate_values(LocalDate value1, LocalDate value2, LocalDate value3) {
    Set<LocalDate> set = new HashSet<LocalDate>();
    set.add(value1);
    set.add(value2);
    set.add(value3);
    assertThat(set).hasSize(3);
}
```

2021-03-21 08:37 UTC, jwChung commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +            .isBetween(LocalDateTime.now().minusDays(DateAndTimeGenerator.RANGE_DAYS),
차라리 ㅋㅋㅋ

그래도 논의를 해보는 게 좋을 것 같아서 https://github.com/JavaUnit/AutoParams/issues/87 이슈를 만들었습니다.

2021-03-21 09:26 UTC, jwChung reviewed
사소한 의견 몇 가지 드리니 검토 부탁드립니다.  randomness는 테스트하기 불가능하거나 어렵습니다. 그래서 테스트 작성이 어렵게 느껴지는군요.

해결하려는 문제는 현재 min~max 값 범위를 고정하는 장치(eg. Random 외부에서 주입)가 없어서 모든 경우를 테스트하는 것은 불가능하다고 생각합니다. 그래서 @gyuwon 님이 말씀하시는https://github.com/JavaUnit/AutoParams/pull/83#discussion_r598238138 이 정도가 최선이지 않을까 합니다.

2021-03-21 09:26 UTC, jwChung commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +    void sut_LocalDate_randomness(LocalDate value1, LocalDate value2) {
현재 모든 테스트 메소드가 완전한 문장 형태로 표현되고 있습니다. 가급적 이렇게 작성해주시면 감사하겠습니다.

2021-03-21 09:26 UTC, jwChung commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +        assertThat(value1.toString()).isNotEqualTo(value2.toString());
이 assert는 어떤 의미가 있을까요?

2021-03-21 09:26 UTC, jwChung commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +                LocalDate.now().plusDays(RANGE_DAYS));
실패를 현재 프로덕션 코드를 넣거나 빼더라도 이 assert들은 통과합니다. 그래서 저는 이 assert들이 불필요하게 느껴지는데, 어떻게 생각하세요?

아울러 만약 이 assert들이 필요필요하다면, 다른 테스트 메소드를 작성할 것 같습니다. 현재 테스트 메소는 여러 테스트를 한 곳에 작성한 느낌이 듭니다. 이런 경우 첫 assert가 실패하면 이어지는 assert에 진단 결과를 받을 수 없는 단점이 있습니다.

2021-03-21 09:26 UTC, jwChung commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +        assertThat(value1).isNotEqualTo(value2);
:+1:

2021-03-21 13:29 UTC, jwChung commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +                                                                    LocalDateTime value2) {
```suggestion
    void sut_correctly_creates_local_date_time_with_arbitrary_value(
        LocalDateTime value1, LocalDateTime value2) {
```

다른 코드의 포멧과 일관되게 이렇게 수정하는 것이 어떨까요?

2021-03-21 13:38 UTC, cg4jins commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +                                                                    LocalDateTime value2) {
수정했습니다.

2021-03-21 15:43 UTC, jwChung commented on autoparams/src/main/java/org/javaunit/autoparams/DateAndTimeGenerator.java
> +    }
LocalDate 범위가 2년 전/후가 왜 기준이 되는지 고민할 필요가 있을 것 같습니다. LocalTime은 시/분 뿐만 아니라 초/나노초에 대한 임의성까지 포함하는 것이 어떨까 합니다.

그래서 전 다음과 같이 이 두 값을 최소~최대 값으로 표현하는게 어떨까 생각해봤습니다. 

---------------------------

```java
long inclusiveMin = LocalDate.MIN.toEpochDay();
long exclusiveMax = LocalDate.MAX.toEpochDay() + 1;
long randomEpochDay = RANDOM.nextLong(inclusiveMin, exclusiveMax);
LocalDate.ofEpochDay(randomEpochDay);
```

---------------------------------

```java
long inclusiveMin = LocalTime.MIN.toNanoOfDay();
long exclusiveMax = LocalTime.MAX.toNanoOfDay() + 1;
long randomNanoOfDay = RANDOM.nextLong(inclusiveMin, exclusiveMax);
LocalTime.ofNanoOfDay(randomNanoOfDay);
```

2021-03-22 00:24 UTC, gyuwon commented on autoparams/src/main/java/org/javaunit/autoparams/DateAndTimeGenerator.java
> +    }
이 의견이 반영된다면 운영 코드가 늘어나니 테스트가 더 필요하겠네요.

2021-03-22 13:55 UTC, cg4jins commented on autoparams/src/main/java/org/javaunit/autoparams/DateAndTimeGenerator.java
> +    }
@jwChung 수정했습니다. 코드 너무 좋아요.

2021-03-23 03:23 UTC, closed without merging