[#71] short 값 생성 지원
JavaUnit/AutoParams pull request #97
Opened 2021-03-22 10:36 UTC by arron-shin

# NOTE
- #71 이슈를 구현합니다.

2021-03-22 12:36 UTC, arron-shin commented
커밋 계정이 꼬여서 부득이하게 force push를 했습니다.

2021-03-22 13:11 UTC, jwChung requested changes

2021-03-22 13:11 UTC, jwChung commented on autoparams/src/test/java/org/javaunit/autoparams/AutoArgumentsProviderSpecs.java
> +
작성하신 테스트 스타일은 초기 [AutoSource가 동작하지 않았을 때 사용 만들어진 것입니다.](https://github.com/JavaUnit/AutoParams/pull/57#discussion_r596180374) 이런 스타일의 테스트는 [변경이 예정되어 있습니다. ](https://github.com/JavaUnit/AutoParams/issues/88)

아쉽지만 AutoSourceSpecs 로 테스트를 옮겨주시면 감사하겠습니다.

2021-03-22 13:14 UTC, jwChung commented on autoparams/src/main/java/org/javaunit/autoparams/ShortGenerator.java
> +    public static short factory() {
이 메소드는 클래스 외부에서 접근할 일이 없을 것 같군요.  접근자를 수정하면 좋겠습니다.

2021-03-23 02:20 UTC, arron-shin commented on autoparams/src/main/java/org/javaunit/autoparams/ShortGenerator.java
> +    public static short factory() {
앗? 네네 바로 수정합니다.

2021-03-23 02:21 UTC, arron-shin commented on autoparams/src/test/java/org/javaunit/autoparams/AutoArgumentsProviderSpecs.java
> +
네, 좋습니다. 사실 히스토리를 몰라서 어디에 작성할지 고민됐었네요. 옮기겠습니다.

2021-03-23 04:47 UTC, gyuwon approved these changes

2021-03-23 05:40 UTC, jwChung approved these changes

2021-03-23 06:53 UTC, arron-shin commented on autoparams/src/main/java/org/javaunit/autoparams/ShortGenerator.java
> +    public static short factory() {
@jwChung 매번 느끼지만 접근제어자에 대해서는 늘 신중해야하는데 자꾸 실수하네요. 작성하는 순간과 커밋하는 시점에 다시 체크해야겠네요. 리뷰 감사합니다.

2021-03-23 11:01 UTC, jwChung commented
@arron-shin 코드 상충이 발생했네요. ㅜㅜ

2021-03-24 02:40 UTC, arron-shin commented
@jwChung 님, 확인해서 수정했습니다.

2021-03-24 02:44 UTC, merged

2021-03-24 02:45 UTC, jwChung commented
@arron-shin 수고 많으셨습니다 :) 👍