[#84] Add builder fix api
JavaUnit/AutoParams pull request #99
Opened 2021-03-22 14:56 UTC by mhyeon-lee

Builder 에 fix API 를 추가합니다.
네이밍, 디자인, Immutable 설계 등에 대해 리뷰 부탁드립니다.

2021-03-23 10:59 UTC, jwChung commented on autoparams/src/main/java/org/javaunit/autoparams/Builder.java
> +        return this;
`ObjectGenerationContext`가 `getObjectGenerator()` getter가 있어서 `ObjectGenerator` 인스턴스를 여기로 받아올 수 있다면,  `FixedObjectGenerator` 같은 걸 만들어 끼워 넣는 방식 한번 생각해봤습니다.

```java
return new Builder(
    this.builderQuery,
    new CompositeObjectGenerator(
        new FixedObjectGenerator(type, value) // type이 같으면 value를 generate 하는 기능
        this.generator
    )
);
```

`ObjectGenerator`로 기능을 확장 확장한다는 점에서  일관성 있어서 좋을 것 같습니다.

2021-03-23 11:06 UTC, mhyeon-lee commented on autoparams/src/main/java/org/javaunit/autoparams/Builder.java
> +        return this;
@jwChung 그것도 괜찮을거 같습니다.

추가적으로 사용자가 사용하는 `Builder` 는 Immutable 하게 설계하는게 좋을까요? 상태를 변경시키는게 좋을까요?
여기서 Builder 는 상태를 변경시키고 fluent 를 위해 this 를 반환했는데요, 
Immutable 하게 설계하면 매번 새로운 Builder 를 생성하고 반환하게 설계될거 같군요

2021-03-23 11:08 UTC, mhyeon-lee commented on autoparams/src/main/java/org/javaunit/autoparams/Builder.java
> +        return this;
@jwChung 의견주신 새로운 CompositeObjectGenerator 는 ObjectGenerationContext 와 어떻게 연결시키는게 좋을까요?

2021-03-23 11:14 UTC, jwChung commented on autoparams/src/main/java/org/javaunit/autoparams/Builder.java
> +        return this;
@mhyeon-lee  

```java
public void test(Builder<Foo> fooBuilder) {
    Builder<Foo> builder1 = fooBuilder.fix(Integer.class, 10);
    builder1.build().integerValue() // == 10
    Builder<Foo> bulider2 = fooBuilder.fix(String.class, "hello");
    bulider2.build().integerValue() // this를 반환하면 10, Immutable이면 임의의 값이겠네요.
}
```

전 Immutable이 끌리긴 하네요.

2021-03-23 11:16 UTC, jwChung commented on autoparams/src/main/java/org/javaunit/autoparams/Builder.java
> +        return (T) this.getObjectGenerationContext().generate(query);
https://github.com/JavaUnit/AutoParams/pull/99#discussion_r599472290

@mhyeon-lee 생성자에선 `ObjectGenerator(CompositeObjectGenerator)`를 받는다면 여기서 만들어도 괜찮을 것 같아요.

```java
return (T) new ObjectGenerationContext(this.generator).generate(query);
```

2021-03-23 11:17 UTC, mhyeon-lee commented on autoparams/src/main/java/org/javaunit/autoparams/Builder.java
> +        return (T) this.getObjectGenerationContext().generate(query);
넵 의견 주신 방향으로 변경해보겠습니다.

2021-03-23 11:32 UTC, mhyeon-lee commented on autoparams/src/main/java/org/javaunit/autoparams/Builder.java
> +        return this;
@jwChung 
아래 커밋으로 의견 주신 내용 반영하고 Immutable Builder 관련 테스트도 추가했습니다.
의도하신것과 맞는지 리뷰 부탁드립니다.
https://github.com/JavaUnit/AutoParams/pull/99/commits/81a0712ca46351dc1ee08355a252a7fc5a4fff60

2021-03-23 12:57 UTC, jwChung commented on autoparams/src/main/java/org/javaunit/autoparams/Builder.java
> +    public Builder<T> fix(Class<?> type, Object value) {
`Class<?>`와 `Object` 에 제네릭 타입을 넣어서 assignable 을 표현해주면 어떨까요?

2021-03-23 12:57 UTC, jwChung commented on autoparams/src/main/java/org/javaunit/autoparams/ObjectGenerationContext.java
> +    }
`getGenerator()` 로 노출하지 않고 아래 두 가지 방법이 더 생각나는데요.

1. `ObjectGenerationContext`가 `ObjectGenerator` 를 다음과 같이 구현해버리는 방법
    "다른 context 를 이용해서도 값을 생성할 수 있다" 이런 의미가 되겠네요.

    ```java
    public Optional<Object> generate(ObjectQuery query, ObjectGenerationContext context) {
        return this.generator.generate(query, context);
    }
    ```
2. `InsertFirst`
    ```java
    public ObjectGenerationContext InsertFirst(ObjectGenerator generator) {
        return new ObjectGenerationContext(new CompositeObjectGenerator(generator, this.generator));
    }
    ```
    
어떤 방법이 괜찮을까요?

2021-03-23 13:04 UTC, mhyeon-lee commented on autoparams/src/main/java/org/javaunit/autoparams/ObjectGenerationContext.java
> +    }
2번째가 더 좋을거 같은데요 insertFirst 말고 더 좋은 이름이 있으면 좋을거 같은데 떠오르진 않네요
(insertFirst 는 상태를 바꾸는 느낌이네요)

2021-03-23 13:09 UTC, jwChung commented on autoparams/src/main/java/org/javaunit/autoparams/ObjectGenerationContext.java
> +    }
@mhyeon-lee  심지어 제가 대문자로 썼군요 ㅋㅋ

2021-03-23 13:10 UTC, jwChung commented on autoparams/src/main/java/org/javaunit/autoparams/ObjectGenerationContext.java
> +    }
이건 조금 더 천천히 고민해도 되긴하겠네요.

2021-03-23 13:12 UTC, mhyeon-lee commented on autoparams/src/main/java/org/javaunit/autoparams/ObjectGenerationContext.java
> +    }
@jwChung 네 우선은 generator 를 getter 로 노출된 형태로 두고 @gyuwon 님의 의견을 들어보겠습니다.

2021-03-23 13:46 UTC, jwChung approved these changes

2021-03-24 05:14 UTC, gyuwon commented on autoparams/src/main/java/org/javaunit/autoparams/ObjectGenerationContext.java
> +    }
현재대로 두되 `ObjectGenerationContext` 형식은 이후 API로 노출될 가능성이 있으니 `public`을 빼는 건 어떨까요?

2021-03-24 05:21 UTC, gyuwon commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +            assertThat(value.getValue5()).isEqualTo(fixIntArray);
`isSameAs`를 쓰는 것이 좋을 것 같습니다.

2021-03-24 05:21 UTC, gyuwon commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +    void sut_complex_object_builder_fix_int(int fixInt, Builder<ComplexObject[]> builder) {
이 테스트에서 `sut`는 `builder`를 뜻하는 것 같은데 테스트 이름에 둘 다 등장해서 좀 어색하고 문장 완성이 안되는 것 같습니다.

그리고 하나의 테스트에서 여러가지를 검증한느 것 같은 느낌이 들기도 합니다.

2021-03-24 05:52 UTC, mhyeon-lee commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +    void sut_complex_object_builder_fix_int(int fixInt, Builder<ComplexObject[]> builder) {
그러네요 int 와 int[] 의 속성 두가지를 검증하고 있었네요 
테스트 분리했습니다.

2021-03-24 05:53 UTC, mhyeon-lee commented
@gyuwon @jwChung 리뷰 사항 반영하고 squash 했습니다.

2021-03-25 11:14 UTC, jwChung approved these changes

2021-03-26 00:15 UTC, mhyeon-lee commented
@gyuwon 추가 리뷰나 의견이 있으실까요?

2021-03-27 10:54 UTC, gyuwon commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +    void sut_complex_object_fix_int(int fixInt, Builder<ComplexObject[]> builder) {
이 테스트가 검증하려는 하나의 명세가 무엇인지 이해하지 못했습니다.

2021-03-27 11:01 UTC, mhyeon-lee commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +    void sut_complex_object_fix_int(int fixInt, Builder<ComplexObject[]> builder) {
아래 테스트로 분리해놓고 여기에 분리된 테스트 검증을 지우지 않았군요;  수정하겠습니다.
https://github.com/JavaUnit/AutoParams/pull/99/files#diff-4596ca34c668bd2e4dbaba025b1b7db061cf23c52f80f728f0267d37b80131fbR386

2021-03-27 11:06 UTC, mhyeon-lee commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +    void sut_complex_object_fix_int(int fixInt, Builder<ComplexObject[]> builder) {
@gyuwon 
아래 커밋에서 수정했습니다. 혹시 리뷰로 의도하신 부분이 다른 부분이면 말씀해주시기 바랍니다.
https://github.com/JavaUnit/AutoParams/pull/99/commits/34571c50767c5cef6d14b5bc02c2b7c8fabd55a6

AutoSourceSpecs 테스트가 test 패키 밑으로 이사가고 있어서 conflicts 가 났네요 rebase 를 하면서 이사가야겠네요
리뷰가 완료되면 rebase 하면서 정리하겠습니다.

2021-03-27 11:12 UTC, gyuwon commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +    void sut_fix_then_immutable(Builder<ComplexObject> builder) {
`Builder<T>`가 불변성을 가져야 하는 이유가 궁금합니다.

2021-03-27 11:12 UTC, gyuwon commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +    void sut_complex_object_fix_int(int fixInt, Builder<ComplexObject[]> builder) {
테스트 케이스가 모두 배열을 대상으로 하는 이유가 궁금합니다.

2021-03-27 11:14 UTC, mhyeon-lee commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +    void sut_fix_then_immutable(Builder<ComplexObject> builder) {
@gyuwon 
여기에서 @jwChung 님이 의견을 주셔서 Immutable 로 변경했습니다.
https://github.com/JavaUnit/AutoParams/pull/99#discussion_r599475866

사용자 케이스에 해당하므로 @gyuwon 님은 어떤 방향이 나을지 의견 부탁드립니다.

2021-03-27 11:21 UTC, mhyeon-lee commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +    void sut_complex_object_fix_int(int fixInt, Builder<ComplexObject[]> builder) {
기억으로 `테스트를 먼저 작성하면서 문제 정의시 fix 된 값은 N 건 생성된 객체 모두에 고정된다` 로 정의하고 시작했던거 같군요
문제 정의를 필요한것 보다 크게 잡은거 같기도 하군요

2021-03-27 11:25 UTC, gyuwon commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +    void sut_fix_then_immutable(Builder<ComplexObject> builder) {
그랬군요. 제가 확인하지 못했습니다. 읽어보고 피드백 드리겠습니다.

2021-03-27 11:33 UTC, gyuwon commented on autoparams/src/main/java/org/javaunit/autoparams/Builder.java
> +        return this;
저는 사용하는 입장에서 불편해지지 않을까 싶습니다. 예를 들어 몇개의 속성을 고정하고 하나의 속성을 다르게 고정해서 데이터 2개를 생성하고 싶다면 두개의 빌더를 만들기 위해 많은 코드를 작성해야 할 듯 해요.

```java
@ParameterizedTest
@AutoSource
void testMethod(Builder<Entity> builder) {
    // Arrange
    UUID uuid = UUID.randomUUID();

    Entity entity1 = builder
        .fix(int.class, 10)
        .fix(String.class "foo")
        .fix(UUID.class, uuid)
        .fix(double.class, 1.0)
        .build();

    Entity entity2 = builder
        .fix(int.class, 10)
        .fix(String.class "foo")
        .fix(UUID.class, uuid)
        .fix(double.class, 2.0)
        .build();

    // Act

    // Assert
}
```

빌더가 불변하지 않다면 이렇게 되겠죠.

```java
@ParameterizedTest
@AutoSource
void testMethod(Builder<Entity> builder) {
    // Arrange
    builder
        .fix(int.class, 10)
        .fix(String.class "foo")
        .fix(UUID.class, UUID.randomUUID());

    Entity entity1 = builder.fix(double.class, 1.0).build();
    Entity entity2 = builder.fix(double.class, 2.0).build();

    // Act

    // Assert
}
```

2021-03-27 11:37 UTC, gyuwon commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +    void sut_complex_object_fix_int(int fixInt, Builder<ComplexObject[]> builder) {
우리가 꼭 TDD를 해야 한다고 규정한 적은 없지만 TDD를 했다면 작성하지 않아도 됐을 것 같은 테스트가 많이 작성된 것 같습니다. 그러니까 한 두개의 테스트를 통과할 만큼의 운영코드를 쓰고나서 이후 테스트들은 작성하면 바로 성공할 듯 해요. 그래서 테스트를 더 이해하기 어려운 것이 아닌가 싶은데 테스트 내용은 유지하더라도 작은 단위로 간단하게 쓰여지면 어떨까 싶습니다.

2021-03-27 11:43 UTC, jwChung reviewed
@mhyeon-lee 님 테스트 이름 작성에는 여러가지 스타일이 있을껀데요. 특별히 그럴싸해보였지만 실제로 사용하면 전 별로였던  [`[UnitOfWork_StateUnderTest_ExpectedBehavior]`](https://osherove.com/blog/2005/4/3/naming-standards-for-unit-tests.html) 같은 스타일도 있고요.

현재 우리는 `sut_does_something` 이런 스타일로 되도록 완성된 하나의 문장으로 작성하고 있습니다. 이 관점에서 제가 아래와 같이 몇 가지 테스트 이름을  작성해보았습니다. :)

2021-03-27 11:43 UTC, jwChung commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +    void sut_complex_object_fix_int(int fixInt, Builder<ComplexObject[]> builder) {
```
sut_correctly_fixes_int_value_in_comlex_object_array
```

2021-03-27 11:43 UTC, jwChung commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +    void sut_complex_object_fix_int_fixed_array_element(
```
sut_correctly_fixes_int_array_in_comlex_object_array
```

2021-03-27 11:43 UTC, jwChung commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +    void sut_complex_object_fix_int_and_int_array_fixed_each_other(
```
sut_correctly_fixes_int_value_and_int_array_in_comlex_object_array
```

2021-03-27 11:43 UTC, jwChung commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +    void sut_complex_object_fix_int_and_Integer_fixed_each_other(
```
sut_correctly_fixes_int_and_integer_values_in_comlex_object_array
```

2021-03-27 11:46 UTC, mhyeon-lee commented
@jwChung 의견 감사합니다
제안 주신 형식으로 수정해보겠습니다

2021-03-27 11:51 UTC, mhyeon-lee commented on autoparams/src/test/java/org/javaunit/autoparams/AutoSourceSpecs.java
> +    void sut_complex_object_fix_int(int fixInt, Builder<ComplexObject[]> builder) {
@gyuwon 의견 감사합니다
추가로 사후 테스트 작성한 내용들이 집중을 못하게 만든거 같네요

2021-03-27 12:08 UTC, jwChung commented on autoparams/src/main/java/org/javaunit/autoparams/Builder.java
> +        return this;
@gyuwon @mhyeon-lee 

```java
@ParameterizedTest
@AutoSource
void testMethod(Builder<Entity> builder) {
    // Arrange
    Builder<Entity> newBuilder = builder
        .fix(int.class, 10)
        .fix(String.class "foo")
        .fix(UUID.class, UUID.randomUUID());

    Entity entity1 = newBuilder
        .fix(double.class, 1.0)
        .fix(String.class, "entity1")
        .build();
    Entity entity2 = newBuilder
        .fix(double.class, 2.0)
        .build();

    // Act

    // Assert
}
```

이렇게 중복은 제거할 수 있을껀데요.

위 entity1, entity2 를 만드는 경우에  독립적인 context(`ObjectGenerationContext`)를 제공하는 것이 의미 있을 것 같아 immutable을 제안드렸습니다. `entity2.getName()` 이라는 `Stirng` 값이 `"entity1"`가 아니라 `"foo"` 로 나오는 시나리오입니다.

논의가 더 필요할 것 같아서 Resolved된 스레드 Unresolved로 돌렸습니다.

2021-03-27 13:09 UTC, gyuwon commented on autoparams/src/main/java/org/javaunit/autoparams/Builder.java
> +        return this;
말씀하신 경우는 빌더가 가변하다면 이렇게 되겠네요.

```java

@ParameterizedTest
@AutoSource
void testMethod(Builder<Entity> builder) {
    // Arrange
    builder
        .fix(int.class, 10)
        .fix(UUID.class, UUID.randomUUID());

    Entity entity1 = builder
        .fix(double.class, 1.0)
        .fix(String.class "entity1")
        .build();

    Entity entity2 = builder
        .fix(double.class, 2.0)
        .fix(String.class "foo")
        .build();

    // Act

    // Assert
}
```

보여주신 예제에서도 제가 우려하는 부분이 발생했는데요, `newBuilder`가 등장한 것입니다. 개체 생성 기준이 복잡해지면 코드 중복을 줄이기 위해 계속 새로운 빌더를 만들고 이름을 지어야 할 것 같아요.

2021-03-27 13:45 UTC, jwChung commented on autoparams/src/main/java/org/javaunit/autoparams/Builder.java
> +        return this;
bulder 이름을 재사용한다거나, 새 의미 있는 이름을 지어주는 경우도 필요할 수도 있을 것 같습니다.

`fix(...)` 가 `void`를 반환한다면 mutable이 이해되는데요. `Builder<T>`을 반환하면 이게 `this` 인지 새 `Builder<T>` 인스턴스인지 확인하는 일이 생길 것 같습니다.

@mhyeon-lee 님은 어떠세요?

2021-03-27 14:01 UTC, gyuwon commented on autoparams/src/main/java/org/javaunit/autoparams/Builder.java
> +        return this;
Fluent 빌더 패턴은 일반적이라 혼동되는 일이 있을까 싶습니다. .NET 컨테이너 만들 때 `Add...` 많이 해보셨죠? 그 때 반환값이 `this`인지 새 인스턴스인지 확인해 보신 적은 한 번도 없으실 것 같네요. :)

https://dzone.com/articles/fluent-builder-pattern
https://github.com/MilindAtGithub/fluentbuilder/blob/master/src/main/java/com/milind/fluentbuilder/Email.java

오히려 불변성이 많은 분들에게 낯설지 않을까 싶습니다.

2021-03-27 14:47 UTC, jwChung commented on autoparams/src/main/java/org/javaunit/autoparams/Builder.java
> +        return this;
builder 를 사용할 때 immutable/mutable 을 따지지 않고 사용한 경우가 대부분입니다. 하지마 다음과 같이 bulider를 mutable 인지확인이 필요할 때는 `this`를 반환하는지 확인이 필요했습니다.

```java
@ParameterizedTest
@AutoSource
void testMethod(Builder<Entity> builder) {
    Entity entity1 = builder.fix(double.String, "foo").build();
    Entity entity2 = builder.build();
    // entity2.getName() == "foo" ???
}
```

말씀하신 C# 예제나 롬복에서 만들어주는 단순한 빌더를 넘어 다음의 예제처럼 빌드파트 별 순서가 필요할 수도 있습니다.

1. 생성자 선택 전략을 먼저 지정(1단계는 옵션, 디폴트 생성자 선택 전략을 사용하면서 바로 2단계 가능)
2. fix
3. build

이런 좀 더 복잡한 fluent API를 표현하려면, `fix` 가 `Builder<T>` 타입이 아니라 다른 타입의 인스턴스를 반환할 필요도 생깁니다. 이런 때 `this` 를 반환한다고 가정하지는 않을 것 같습니다.

2021-03-27 15:16 UTC, gyuwon commented on autoparams/src/main/java/org/javaunit/autoparams/Builder.java
> +        return this;
위 예제에서는 혼란이 다소 느껴지기도 하네요. 그렇다면 저는 AutoFixture의 `Customize` 메서드 처럼 동작하는 것이 직관적일 것 같아요. `fix` 메서드가 `void` 형식이 되도록요.

그런데 이 정도 주제는 PR이 아니라 이슈에서 논의해야 할 것 같은 느낌이네요.

2021-03-29 01:34 UTC, mhyeon-lee commented on autoparams/src/main/java/org/javaunit/autoparams/Builder.java
> +        return this;
@gyuwon @jwChung 일요일 내내 몸이 안좋아서 이제 피드백 합니다.

저는 빌더 패턴에서는 내부를 보기 전에는 기본적으로 Mutable 로 기대할거 같습니다.
기본 Builder 는 mutable 하되, Immutable 이 필요하다면 ImmutableBuilder 타입을 따로 만드는게 덜 헷갈릴거 같다는 생각도 듭니다.

아래 별도 이슈 생성했습니다.
https://github.com/JavaUnit/AutoParams/issues/146

2021-03-30 08:33 UTC, mhyeon-lee commented
@gyuwon @jwChung 
회사일이 바빠서 이제야 정리했습니다.
@gyuwon 님이 많이 진행해주셔서 rebase 하니까 단순해졌네요

리뷰 부탁드립니다.

2021-03-30 09:29 UTC, jwChung approved these changes

2021-04-03 02:49 UTC, gyuwon requested changes

2021-04-03 02:49 UTC, gyuwon commented on autoparams/src/test/java/org/javaunit/autoparams/test/SpecForBuilderFix.java
> +class SpecForBuilderFix {
`SpecsForBuilder`로 수정 부탁드립니다.

2021-04-03 02:49 UTC, gyuwon commented on autoparams/src/test/java/org/javaunit/autoparams/test/SpecForBuilderFix.java
> +    void sut_correctly_fixes_int_value_in_complex_object_int(
운영 코드를 보면 테스트 케이스는 이것 하나만 있어도 충분할 것 같습니다. 아래 두 개가 더 추가된 이유가 궁금합니다.

2021-04-03 02:49 UTC, gyuwon commented on autoparams/src/test/java/org/javaunit/autoparams/test/SpecForBuilderFix.java
> +    void sut_correctly_fixes_int_value_in_complex_object_int(
`sut_correctly_fixes_int_value`라고만 해도 테스트 하려는 기능의 의미가 충분히 전달되지 않을까 싶습니다.

2021-04-03 03:11 UTC, mhyeon-lee commented on autoparams/src/test/java/org/javaunit/autoparams/test/SpecForBuilderFix.java
> +    void sut_correctly_fixes_int_value_in_complex_object_int(
@gyuwon 
#84 에서 도출한 아래 요구사항을 테스트로 남겨 놓은건데요

- int.class 와 Integer.class fix 는 구분된다.
- int.class fix 는 int[].class 의 element 를 fix 한다

내부 구조 리팩터시 요구사항을 만족하는지를 위한 회귀 테스트로 남겨놓았습니다.

불필요한 테스트로 보면 될까요?

2021-04-03 03:21 UTC, gyuwon commented on autoparams/src/test/java/org/javaunit/autoparams/test/SpecForBuilderFix.java
> +    void sut_correctly_fixes_int_value_in_complex_object_int(
@mhyeon-lee 지금은 우리가 TDD를 강제하는 것은 아니니 제거해야 하는 건 아니라고 생각합니다. 그래서 삭제를 요청하기 보다는 어떤 이유인지 여쭤본거에요.

2021-04-03 03:35 UTC, gyuwon requested changes

2021-04-03 03:35 UTC, gyuwon commented on autoparams/src/test/java/org/javaunit/autoparams/test/SpecsForBuilderFix.java
> +    void sut_correctly_fixes_int_array_elements(
`sut_correctly_fixes_elements_of_arraay`로 하고 `ComplexObject` 보다는 `int[]`를 만들어 보는 것이 좀 더 의도를 명확히 표현할 것 같습니다.

2021-04-03 03:35 UTC, gyuwon commented on autoparams/src/test/java/org/javaunit/autoparams/test/SpecsForBuilderFix.java
> +        int fixInt, Builder<ComplexObject> builder) {
`fixInt`를 `fixedInt`로 변경해주세요.

2021-04-03 03:35 UTC, gyuwon commented on autoparams/src/test/java/org/javaunit/autoparams/test/SpecsForBuilderFix.java
> +        int fixInt, Builder<ComplexObject> builder) {
`fixInt`를 `fixedInt`로 변경해주세요.

2021-04-03 03:35 UTC, gyuwon commented on autoparams/src/test/java/org/javaunit/autoparams/test/SpecsForBuilderFix.java
> +    void sut_correctly_fixes_int_and_integer_values(
테스트 이름을 `sut_separately_fixes_primitive_value_and_boxed_value`로 변경하고 이렇게 테스트 하는 것이 단순하고 명확할 것 같습니다.

```java
    @ParameterizedTest
    @AutoSource(repeat = 10)
    void sut_separately_fixes_primitive_value_and_boxed_value(int fixedInt, Builder<Integer> builder) {
        Integer actual = builder.fix(int.class, fixedInt).build();
        assertThat(actual).isNotEqualTo(fixedInx);
    }
```

2021-04-03 04:22 UTC, mhyeon-lee commented on autoparams/src/test/java/org/javaunit/autoparams/test/SpecsForBuilderFix.java
> +    void sut_correctly_fixes_int_and_integer_values(
그러네요 의견 감사합니다.

반영해서 squash 했습니다.

2021-04-03 04:30 UTC, gyuwon approved these changes

2021-04-03 04:30 UTC, merged